-- Migration: Multisatuan & Multi Harga

CREATE TABLE IF NOT EXISTS product_units (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  product_id INT UNSIGNED NOT NULL,
  unit_name VARCHAR(32) NOT NULL,
  conversion_value INT NOT NULL DEFAULT 1,
  purchase_price DECIMAL(18,2) NOT NULL DEFAULT 0,
  sell_price DECIMAL(18,2) NOT NULL DEFAULT 0,
  barcode VARCHAR(64) UNIQUE NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_pu_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS product_prices (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  product_id INT UNSIGNED NOT NULL,
  product_unit_id INT UNSIGNED NULL,
  customer_category VARCHAR(64) NOT NULL DEFAULT 'umum',
  price DECIMAL(18,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_pp_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  CONSTRAINT fk_pp_unit FOREIGN KEY (product_unit_id) REFERENCES product_units(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE transaction_items 
  ADD COLUMN unit_name VARCHAR(32) NOT NULL DEFAULT 'PCS',
  ADD COLUMN conversion_value INT NOT NULL DEFAULT 1;
